name: Leo Release
on:
  push:
    branches: [ build-for-different-targets ]
    tags:
      - 'v*.*.*'

env:
  RUST_BACKTRACE: full
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  ubuntu:
    name: "target: ${{ matrix.cfg.target }}"
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.cfg.experimental }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { target: aarch64-unknown-linux-gnu, features: --features vendored-openssl, experimental: true }
          - { target: arm-unknown-linux-gnueabi, features: --features vendored-openssl, experimental: true }
          - { target: x86_64-unknown-linux-gnu, features: "", experimental: false }
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
          target: ${{ matrix.cfg.target }}

      - name: Install dependencies for arm64
        if: ${{ matrix.cfg.target == 'aarch64-unknown-linux-gnu' }}
        run: |
          sudo apt-get install -y gcc-aarch64-linux-gnu libc6-dev-i386 g++-multilib

      - name: Install dependencies for arm
        if: ${{ matrix.cfg.target == 'arm-unknown-linux-gnueabi' }}
        run: |
          sudo apt-get install -y gcc-arm-linux-gnueabi libc6-dev-i386 g++-multilib

      - name: Build Leo
        run: |
          cargo build --release --verbose --workspace ${{ matrix.cfg.features }} --target=${{ matrix.cfg.target }} && strip target/${{ matrix.cfg.target }}/release/leo

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Zip
        run: |
          zip -r leo-${{ steps.get_version.outputs.version }}-${{ matrix.cfg.target }}.zip target/${{ matrix.cfg.target }}/release/leo

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            leo-${{ steps.get_version.outputs.version }}-${{ matrix.cfg.target }}.zip

  macos:
    name: "target: ${{ matrix.cfg.target }}"
    runs-on: macos-latest
    continue-on-error: ${{ matrix.cfg.experimental }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { target: aarch64-apple-darwin, experimental: true }
          - { target: x86_64-apple-darwin, experimental: false }
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
          target: ${{ matrix.cfg.target }}

      - name: Build Leo
        run: |
          cargo build --release --workspace --target=${{ matrix.cfg.target }} && strip target/${{ matrix.cfg.target }}/release/leo

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Zip
        run: |
          zip -r leo-${{ steps.get_version.outputs.version }}-${{ matrix.cfg.target }}.zip target/${{ matrix.cfg.target }}/release/leo

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            leo-${{ steps.get_version.outputs.version }}-${{ matrix.cfg.target }}.zip

  windows:
    name: "target: ${{ matrix.cfg.target }}"
    runs-on: windows-latest
    continue-on-error: ${{ matrix.cfg.experimental }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { target: aarch64-pc-windows-msvc, experimental: true }
          - { target: i686-pc-windows-msvc, experimental: true }
          - { target: x86_64-pc-windows-msvc, experimental: false }
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
          target: ${{ matrix.cfg.target }}

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "11"
          directory: ${{ runner.temp }}/llvm

      - name: Set LIBCLANG_PATH
        run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV

      - name: Set up MinGW
        if: ${{ matrix.cfg.target == 'i686-pc-windows-gnu' }}
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x86

      - name: Build Leo
        run: |
          cargo build --release --workspace --target=${{ matrix.cfg.target }}

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Zip
        run: |
          Compress-Archive target/${{ matrix.cfg.target }}/release/leo.exe leo-${{ steps.get_version.outputs.version }}-${{ matrix.cfg.target }}.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            leo-${{ steps.get_version.outputs.version }}-${{ matrix.cfg.target }}.zip
